language: python
before_install: build/install-dependencies.sh
script: build/build_travis.sh
deploy:
    provider: script
    script: build/deploy_jira-issue.sh
    on:
        all_branches: true
        condition: "$TRAVIS_BRANCH != master"
    skip_cleanup: true
sudo: required
